export const Actions = {
    USER_INIT: 'USER_INIT',

    FORM_REGISTER: 'FORM_REGISTER',
    FORM_REGISTER_FNAME_UPDATE: 'FORM_REGISTER_FNAME_UPDATE',
    FORM_REGISTER_LNAME_UPDATE: 'FORM_REGISTER_LNAME_UPDATE',
    FORM_REGISTER_EMAIL_UPDATE: 'FORM_REGISTER_EMAIL_UPDATE',
    FORM_REGISTER_PASSWORD_UPDATE: 'FORM_REGISTER_PASSWORD_UPDATE',
    FORM_REGISTER_CONFIRM_UPDATE: 'FORM_REGISTER_CONFIRM_UPDATE',

    LOG_IN_EMAIL_UPDATE: 'LOG_IN_EMAIL_UPDATE',
    LOG_IN_PASSWORD_UPDATE: 'LOG_IN_PASSWORD_UPDATE',
    LOG_IN: 'LOG_IN'
};