export const ChangePassActions = {
    CHG_PASS_INIT: 'CHG_PASS_INIT',
    CHG_PASS_PASSWORD_UPDATE: 'CHG_PASS_PASSWORD_UPDATE',
    CHG_PASS_CONFIRM_UPDATE: 'CHG_PASS_CONFIRM_UPDATE',
    CHG_PASS_SUBMIT: 'CHG_PASS_SUBMIT',

};