export const LogInActions = {
    LOG_IN_EMAIL_UPDATE: 'LOG_IN_EMAIL_UPDATE',
    LOG_IN_PASSWORD_UPDATE: 'LOG_IN_PASSWORD_UPDATE',
    LOG_IN: 'LOG_IN',
    LOG_IN_INIT: 'LOG_IN_INIT',
    LOG_IN_FORGOT_PASS: 'LOG_IN_FORGOT_PASS',
    LOG_IN_RESET_PASS: 'LOG_IN_RESET_PASS',
    LOG_IN_FORGOT_MSG: 'LOG_IN_FORGOT_MSG',
    LOG_IN_SEND_NEW_MSG: 'LOG_IN_SEND_NEW_MSG'
};