USE [master]
GO

/****** Object:  Database [Resume_iTechArt]    Script Date: 25.08.2017 11:04:15 ******/
CREATE DATABASE [Resume_iTechArt]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Resume_iTechArt', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS2016\MSSQL\DATA\Resume_iTechArt.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Resume_iTechArt_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS2016\MSSQL\DATA\Resume_iTechArt_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Resume_iTechArt] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Resume_iTechArt].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Resume_iTechArt] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Resume_iTechArt] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Resume_iTechArt] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Resume_iTechArt] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Resume_iTechArt] SET ARITHABORT OFF 
GO

ALTER DATABASE [Resume_iTechArt] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Resume_iTechArt] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Resume_iTechArt] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Resume_iTechArt] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Resume_iTechArt] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Resume_iTechArt] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Resume_iTechArt] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Resume_iTechArt] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Resume_iTechArt] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Resume_iTechArt] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Resume_iTechArt] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Resume_iTechArt] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Resume_iTechArt] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Resume_iTechArt] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Resume_iTechArt] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Resume_iTechArt] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Resume_iTechArt] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Resume_iTechArt] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Resume_iTechArt] SET  MULTI_USER 
GO

ALTER DATABASE [Resume_iTechArt] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Resume_iTechArt] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Resume_iTechArt] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Resume_iTechArt] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Resume_iTechArt] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Resume_iTechArt] SET QUERY_STORE = OFF
GO

USE [Resume_iTechArt]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Resume_iTechArt] SET  READ_WRITE 
GO


