USE CommercialNetwork
GO

ALTER TABLE [Order] ADD CONSTRAINT FK_Order_Shop
FOREIGN KEY (FK_ShopID) REFERENCES Shop(ShopID) ON DELETE CASCADE
GO

ALTER TABLE [Order] ADD CONSTRAINT FK_Order_Product
FOREIGN KEY (FK_ProductID) REFERENCES Product(ProductID) ON DELETE CASCADE
GO


ALTER TABLE [ShopProductRelation] ADD CONSTRAINT FK_ShopProductRelation_Shop
FOREIGN KEY (FK_ShopID) REFERENCES Shop(ShopID) ON DELETE CASCADE
GO

ALTER TABLE [ShopProductRelation] ADD CONSTRAINT FK_ShopProductRelation_Product
FOREIGN KEY (FK_ProductID) REFERENCES Product(ProductID) ON DELETE CASCADE
GO


ALTER TABLE [OrderCustomerRelation] ADD CONSTRAINT FK_OrderCustomerRelation_Order
FOREIGN KEY (FK_OrderID) REFERENCES [Order](OrderID) ON DELETE CASCADE
GO

ALTER TABLE [OrderCustomerRelation] ADD CONSTRAINT FK_OrderCustomerRelation_Customer
FOREIGN KEY (FK_CustomerID) REFERENCES Customer(CustomerID) ON DELETE CASCADE
GO